# Generated by Django 5.2 on 2025-04-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fidiplus_book',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.book')),
                ('file', models.FileField(upload_to='fidiplus_book/')),
            ],
            bases=('base.book',),
        ),
    ]
